{{- if .Values.kibana.name }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.kibana.name }}
spec:
  version: {{ .Values.kibana.version }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
  podTemplate:
    metadata:
      {{- if .Values.kibana.podAnnotations }}
      annotations:
{{ toYaml .Values.kibana.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: {{ .Values.kibana.limits.memory }}
            cpu: {{ .Values.kibana.cpu }}
      serviceAccountName: {{ include "elastic-cluster.elasticsearch.serviceAccountName" $ }}
  secureSettings:
    - secretName: {{ .Values.kibana.name }}-kb-secret-config
{{ end }}
{{- if .Values.fleet.enabled }}
  config:
    xpack.fleet.agents.elasticsearch.host: "https://{{ .Values.elasticsearch.name }}-es-http.{{ .Release.Namespace }}.svc:9200"
    xpack.fleet.agents.fleet_server.hosts: ["https://{{ .Values.fleet.name }}-agent-http.{{ .Release.Namespace }}.svc:8220"]
{{- end -}}
{{- range $key,$value := .Values.kibana.config }}
    {{ $key }}: {{ $value }}
{{- end }}

