{{- if .Values.kibana.name }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.kibana.name }}
spec:
  version: {{ .Values.kibana.version }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: {{ .Values.kibana.limits.memory }}
            cpu: {{ .Values.kibana.cpu }}
  secureSettings:
    - secretName: {{ .Values.kibana.name }}-secret-settings
{{ end }}