{{- if .Values.kibana.name }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.kibana.name }}
spec:
  version: {{ .Values.kibana.version }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
  podTemplate:
    metadata:
      {{- if .Values.kibana.podAnnotations }}
      annotations:
{{ toYaml .Values.kibana.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: {{ .Values.kibana.limits.memory }}
            cpu: {{ .Values.kibana.cpu }}
      serviceAccountName: {{ include "elastic-cluster.elasticsearch.serviceAccountName" $ }}
  secureSettings:
    - secretName: {{ .Values.kibana.name }}-kb-secret-config
{{ end }}
