{{- if .Values.kibana.encryptionKey.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kibana.name }}-kb-secret-config
type: Opaque
data:
  {{- if .Values.kibana.encryptionKey.value }}
    xpack.security.encryptionKey: {{ .Values.kibana.encryptionKey.value | b64enc }}
  {{- else }}
    xpack.security.encryptionKey: {{ randAlphaNum 32 | b64enc }}
  {{ end }}
{{- end }}
