{{- if .Values.kibana.encryptionKey.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: kibana-{{ .Values.kibana.name }}-secret-config
type: Opaque
data:
  {{- if .Values.kibana.encryptionKey.value }}
    xpack.security.encryptionKey: {{ .Values.kibana.encryptionKey.value }}
  {{- else }}
    xpack.security.encryptionKey: {{ randAlphaNum 32 }}
  {{ end }}
{{- end }}