{{- if .Values.elasticsearch.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.elasticsearch.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "elastic-cluster.elasticsearch.serviceAccountName" $ }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.elasticsearch.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.elasticsearch.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
---
{{- if .Values.kibana.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.kibana.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "elastic-cluster.kibana.serviceAccountName" $ }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.kibana.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.kibana.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
---
{{- if .Values.fleet.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.fleet.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "elastic-cluster.fleet.serviceAccountName" $ }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.fleet.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.fleet.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}

