# ----
elasticsearch:
  name: "elasticsearch"
  version: 7.9.0
  nodeSets:
    - name: nset1
      count: 1
      mmap:
        vm_max_map_count: 262144
        enabled: false
      roles:
        - "master"
        - "data"
        - "ingest"
      limits:
        cpu: 0.9
        memory: 2Gi
      heapSize: 1700m  # Use [m for Megabytes, g for gigabytes]
      volumeClaims:
        enabled: true
        class: standard
        size: 512Mi
  service:
    enabled: true
    type: ClusterIP
    # name: elastisearch
  ingress:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # # If 'hosts' is commented out, default ingress is created
    # hosts:
    # - name: elasticsearch.bluebaron.local
    #   path: "/"

    # # tls is handled automatically if 'tls' is empty
    # tls: []

# ----
kibana:
  name: "kibana"
  version: 7.9.0
  # To increase "count" - 'xpack.encryptedSavedObjects.encryptionKey' needs to be set
  count: 1
  encryptionKey:
    enabled: True
    # 'xpack.encryptedSavedObjects.encryptionKey' value:
    value: "" # If blank, a random key will be generated
  limits:
    cpu: 0.5
    memory: 1Gi
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # # If 'hosts' is commented out, default ingress is created
    # hosts:
    # - name: kibana.bluebaron.local
    #   path: "/"

    # # tls is handled automatically if 'tls' is empty
    # tls: []
