image:
  repository: docker.elastic.co/beats/auditbeat
  tag: 7.9.3
  pullPolicy: IfNotPresent

config:
  auditbeat.modules:
  - module: auditd
    # keep this 0 and be more selective in auditd rules to rate-limit without dropping audit events
    rate_limit: 0
    # maximum number of audit messages that will be buffered by the kernel
    backlog_limit: 8196
    # See https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-auditd.html for more info
    audit_rules: |-
      -a never,exit -S all -F pid=26253
      -a always,exit -F arch=b32 -S all -F key=32bit-abi
      -a always,exit -F arch=b64 -S execve,execveat -F key=exec
      -a always,exit -F arch=b64 -S connect,accept,bind -F key=external-access
      -w /etc/group -p wa -k identity
      -w /etc/passwd -p wa -k identity
      -w /etc/gshadow -p wa -k identity
      -a always,exit -F arch=b64 -S open,truncate,ftruncate,creat,openat,open_by_handle_at -F exit=-EACCES -F key=access
      -a always,exit -F arch=b64 -S open,truncate,ftruncate,creat,openat,open_by_handle_at -F exit=-EPERM -F key=access


  - module: file_integrity
    paths:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    - /etc

  - module: system
    datasets:
      - host    # General host information, e.g. uptime, IPs
      - login   # User logins, logouts, and system boots.
      - process # Started and stopped processes
      # - socket  # Opened and closed sockets
      - user    # User information
      - package # Installed, updated, and removed packages
  
    # How often datasets send state updates with the
    # current state of the system (e.g. all currently
    # running processes, all open sockets).
    state.period: 4h
  
    # Enabled by default. Auditbeat will read password fields in
    # /etc/passwd and /etc/shadow and store a hash locally to
    # detect any changes.
    user.detect_password_changes: true
  
    # File patterns of the login record files.
    login.wtmp_file_pattern: /var/log/wtmp*
    login.btmp_file_pattern: /var/log/btmp*      

  processors:
  - add_cloud_metadata:

  - add_docker_metadata:

  - add_kubernetes_metadata:
  # queue: {}
    ## Queue type by name (default 'mem')
    ## The memory queue will present all available events (up to the outputs
    ## bulk_max_size) to the output, the moment the output is ready to server
    ## another batch of events.
    # mem:
      ## Max number of events the queue can buffer.
      # events: 4096

      ## Hints the minimum number of events stored in the queue,
      ## before providing a batch of events to the outputs.
      ## A value of 0 (the default) ensures events are immediately available
      ## to be sent to the outputs.
      # flush.min_events: 2048

      ## Maximum duration after which events are available to the outputs,
      ## if the number of events stored in the queue is < min_flush_events.
      # flush.timeout: 1s

  output.file:
    enabled: false

  output.logstash:
    hosts: [""]
    # Connects directly to the Collector Kubernetes Service without TLS
    ssl.enabled: false
    # Forces connection reset every 2 minutes
    #   to utilize Load Balancing in TCP level
    pipelining: 0
    ttl: 120

  output.elasticsearch:
    enabled: false

  setup.kibana:
    host: ""
    protocol: https
    username: ""
    password: ""
    ssl:
      enabled: true
      certificate_authorities: ["/certs/ca.crt"]

# List of beat plugins
plugins: []
  # - kinesis.so

# Additional container arguments
extraArgs: []
  # - -d
  # - *

# A map of additional environment variables
extraVars: {}
# Add additional volumes and mounts, for example to read other log files on the host
# Extra Environment Values - allows yaml definitions
extraVolumes:
  - name: kb-certs
    secret:
      defaultMode: 420
      secretName: ""

extraVolumeMounts:
  - name: kb-certs
    mountPath: /certs
    readOnly: true

## Labels to be added to pods
podLabels: {}

## Annotations to be added to pods
podAnnotations: {}

resources: {}
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 200Mi
  # requests:
  #  cpu: 100m
  #  memory: 100Mi

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

## Affinity configuration for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
affinity: {}

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

tolerations:
  - operator: Exists